# Generated by Django 3.0.7 on 2020-07-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='slides/')),
            ],
            options={
                'verbose_name': 'Catégorie produit',
                'verbose_name_plural': 'Catégories produits',
            },
        ),
        migrations.CreateModel(
            name='Categories_Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='slides/')),
                ('caractéristique_1', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_1', models.CharField(blank=True, max_length=100)),
                ('caractéristique_2', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_2', models.CharField(blank=True, max_length=200)),
                ('caractéristique_3', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_3', models.CharField(blank=True, max_length=200)),
                ('caractéristique_4', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_4', models.CharField(blank=True, max_length=200)),
                ('caractéristique_5', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_5', models.CharField(blank=True, max_length=200)),
                ('caractéristique_6', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_6', models.CharField(blank=True, max_length=200)),
                ('caractéristique_7', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_7', models.CharField(blank=True, max_length=200)),
                ('caractéristique_8', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_8', models.CharField(blank=True, max_length=200)),
                ('caractéristique_9', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_9', models.CharField(blank=True, max_length=200)),
                ('caractéristique_10', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_10', models.CharField(blank=True, max_length=200)),
                ('caractéristique_11', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_11', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'solution',
                'verbose_name_plural': 'solutions',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='slides/')),
            ],
            options={
                'verbose_name': "Photo page d'accueil",
                'verbose_name_plural': "Photos page d'accueil",
            },
        ),
        migrations.CreateModel(
            name='Slider_a_propos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='slides/')),
            ],
            options={
                'verbose_name': 'photo page a propos',
                'verbose_name_plural': 'photos page a propos',
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='slides/')),
                ('description', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Categorie_produit', verbose_name='catégorie gamme')),
            ],
            options={
                'verbose_name': 'gamme',
                'verbose_name_plural': 'catalogue',
            },
        ),
    ]
