# Generated by Django 3.0.7 on 2020-07-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200713_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_1',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_10',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_11',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_2',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_3',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_4',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_5',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_6',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_7',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_8',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='détail_de_caractéristique_9',
        ),
    ]
