# Generated by Django 3.0.7 on 2020-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200713_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('département', models.CharField(choices=[('C', 'Commercial'), ('D', 'Direction'), ('M', 'Marketing'), ('SC', 'Service client')], default='D', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('fichier', models.FileField(blank=True, max_length=20, upload_to='fichiers/% d/% m/% Y/')),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Slider_a_propos',
            new_name='SliderAPropos',
        ),
    ]
