# Generated by Django 3.0.7 on 2020-07-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200726_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='département',
            new_name='departement',
        ),
    ]
