# Generated by Django 3.0.7 on 2020-07-27 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200727_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
