# Generated by Django 3.0.7 on 2020-09-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200730_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='slides/')),
            ],
            options={
                'verbose_name': 'Produits',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
