# Generated by Django 3.0.7 on 2020-09-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='gamme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Categorie_produit', verbose_name='catégorie gamme'),
            preserve_default=False,
        ),
    ]
