# Generated by Django 3.0.7 on 2020-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_produit_gamme'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
