# Generated by Django 3.0.7 on 2020-09-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_produit_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_titre',
            field=models.TextField(blank=True, verbose_name='Sous titre'),
        ),
        migrations.AddField(
            model_name='produit',
            name='titre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ProduitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, upload_to='slides/')),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Produit', verbose_name='catégorie gamme')),
            ],
        ),
    ]
