# Generated by Django 3.0.7 on 2020-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200924_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Sous titre'),
        ),
    ]
