# Generated by Django 3.0.7 on 2020-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_produit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sous_titre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sous titre'),
        ),
    ]
