# Generated by Django 3.0.7 on 2020-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200927_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_1',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_10',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_11',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_2',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_3',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_4',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_5',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_6',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_7',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_8',
        ),
        migrations.RemoveField(
            model_name='categories_solution',
            name='caractéristique_9',
        ),
        migrations.AddField(
            model_name='categories_solution',
            name='image2',
            field=models.ImageField(blank=True, upload_to='slides/'),
        ),
        migrations.AddField(
            model_name='categories_solution',
            name='text1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categories_solution',
            name='text2',
            field=models.TextField(blank=True),
        ),
    ]
