# Generated by Django 3.0.7 on 2020-09-30 09:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200930_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories_solution',
            name='text1',
            field=models.TextField(blank=True, verbose_name='Grand titre'),
        ),
        migrations.AlterField(
            model_name='categories_solution',
            name='text2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text en plus'),
        ),
    ]
