# Generated by Django 3.0.7 on 2020-09-30 09:47

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200930_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='slides/', verbose_name='Image')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Article')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categories_solution',
            name='image',
            field=models.ImageField(blank=True, upload_to='slides/', verbose_name='Image principale'),
        ),
    ]
