# Generated by Django 3.0.7 on 2020-10-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200930_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Formulaire de contact'},
        ),
    ]
