# Generated by Django 3.0.7 on 2020-10-17 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201017_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=70)),
                ('titre', models.CharField(blank=True, max_length=50)),
                ('sous_titre', models.CharField(blank=True, max_length=100, verbose_name='Sous titre')),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='slides/')),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Categorie_produit', verbose_name='catégorie gamme')),
            ],
            options={
                'verbose_name': 'Produits',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
