# Generated by Django 3.0.7 on 2020-10-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201018_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_solution',
            options={'ordering': ['ordre'], 'verbose_name': 'solution', 'verbose_name_plural': 'solutions'},
        ),
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['ordre']},
        ),
        migrations.AddField(
            model_name='partenaire',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit2',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
