# Generated by Django 3.0.7 on 2020-10-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201018_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['ordre', 'name']},
        ),
    ]
