# Generated by Django 3.0.7 on 2020-10-18 07:56

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201018_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('ordre'), nulls_last=True)]},
        ),
    ]
